on:
  workflow_dispatch:
  push:
    branches:
      - 'main'
    paths:
      - 'package.json'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - id: getremoterelease
        uses: pozetroninc/github-action-get-latest-release@master
        with:
          repository: ${{ github.repository }}
        env:
          remoterelease: ${{ steps.getremoterelease.outputs.release }}
      - name: getlocalrelese
        run: |
          catrelease=`cat ./package.json | grep version | awk -F '"' '{print $4}'`
          echo "localrelease=v$catrelease" >> $GITHUB_ENV
        id: localrelease
      - name: echoenv ${{ env.localrelease }} -${{ env.remoterelease }}  - ${{ steps.getremoterelease.outputs.release }}
        run: |
            echo ${{ env.localrelease }}
            echo ${{ steps.getremoterelease.outputs.release }}
      - name: check release
        if: env.localrelease  == steps.getremoterelease.outputs.release 
        uses: andymckay/cancel-action@0.2
      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          name: ${{ env.localrelease }}
